query ($pageId: Int!) {
  pages {
    exportContent(pageId: $pageId) {
      pageId
      title
      path
      locale
      markdown
      html
      contentType
      description
      createdAt
      updatedAt
    }
  }
}
